### ISSUE TITLE
No coverage information was collected, exit without writing coverage information

### ISSUE THREAD

**Issue by Almenon** [codecov/example-typescript-vscode-extension#3]
This is a blocker for https://github.com/Almenon/AREPL-vscode/issues/17

see https://github.com/gotwarlost/istanbul/issues/262 for information.

When I upgraded instanbul to 1.1.0-alpha.1 I got this error:

```typescript
TypeError: istanbul.Instrumenter is not a constructor
extensionHostProcess.js:712
    at CoverageRunner.setupCoverage (C:\dev\AREPL-vscode\test\index.ts:112:29)
    at Object.run (C:\dev\AREPL-vscode\test\index.ts:55:24)
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:710:539
    at new n.Class.derive._oncancel (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:75:657)
    at t.handleExtensionTests (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:710:508)
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:707:130
    at Object.g [as _notify] (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:68:868)
    at Object.enter (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:72:153)
    at n.Class.derive._creator._run (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:73:970)
    at n.Class.derive._creator._completed (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:73:411)
```

Npm version: 5.6.0
Node version: 9.5.0

**Comment by nixel2007** [comment]
As I can see your repo does not implement all steps needed to collect code coverage for vscode extension. Please, check the Readme and repo content

**Comment by Almenon** [comment]
I implemented the changes locally and did not commit due to the failure.

**Comment by Almenon** [comment]
Recreated the issue.  See https://github.com/Almenon/AREPL-vscode/tree/coverage
